plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'org.letos.letosremote'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'org.letos'
                artifactId = 'letosremote'
                version = android.defaultConfig.versionName
            }
        }
    }
}
